AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yahoo

  Sample SAM Template for yahoo

Resources:
  YahooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: libs/backend/lambdas/src/yahoo/
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        YahooFinance:
          Type: Api
          Properties:
            Path: /yahoo_finance
            Method: post
      Environment:
        Variables:
          ALLOWED_ORIGINS: http://localhost:4200,https://investments-tracker.toondeboer.com

  DynamoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: libs/backend/lambdas/src/dynamodb/
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        DynamoDB:
          Type: Api
          Properties:
            Path: /microservice
            Method: any
      Environment:
        Variables:
          ENVIRONMENT: dev
          ALLOWED_ORIGINS: http://localhost:4200,https://investments-tracker.toondeboer.com
          COGNITO_USER_POOL_ID: us-east-1_liCB4LgDE
          COGNITO_CLIENT_ID: 3o34bbl92faeo9ljo11eebtim2
